import { writeFile, mkdirSync, existsSync } from 'fs';
import * as path from 'path';

const SYSTEM_PROMPT = `You are a code generation assistant for Agent Garden. When the user asks you to create code, output ONLY the code with a filename comment on the very first line.

The filename comment MUST be the first line in this exact format:
// @file: <filename>

For example:
// @file: LoginComponent.tsx

Then output the rest of the code. Do NOT include any explanation text outside the code. The entire response should be valid code that can be saved directly to a file.

If the task implies a specific file type, use the appropriate extension (.ts, .tsx, .css, .json, etc). If no extension is obvious, default to .ts.`;

export interface StreamResult {
  filename: string | null;
  content: string;
}

export class ClaudeService {
  private apiKey: string | undefined;

  constructor() {
    this.apiKey = process.env.ANTHROPIC_API_KEY;
  }

  async streamTask(
    prompt: string,
    onChunk: (text: string, done: boolean) => void
  ): Promise<StreamResult> {
    let fullText = '';

    if (!this.apiKey) {
      const filename = this.inferFilename(prompt);
      const demoResponse = `// @file: ${filename}\n// Generated by Agent Garden\n// Task: ${prompt}\n\nexport function hello() {\n  console.log("Hello from Agent Garden!");\n}\n`;
      const words = demoResponse.split(' ');
      for (const word of words) {
        await new Promise((r) => setTimeout(r, 100));
        onChunk(word + ' ', false);
        fullText += word + ' ';
      }
      onChunk('', true);
    } else {
      const Anthropic = require('@anthropic-ai/sdk');
      const client = new Anthropic({ apiKey: this.apiKey });

      const stream = await client.messages.stream({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4096,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: prompt }],
      });

      for await (const event of stream) {
        if (
          event.type === 'content_block_delta' &&
          event.delta.type === 'text_delta'
        ) {
          onChunk(event.delta.text, false);
          fullText += event.delta.text;
        }
      }
      onChunk('', true);
    }

    const { filename, content } = this.parseResponse(fullText);
    return { filename, content };
  }

  async saveToFile(directory: string, filename: string, content: string): Promise<string> {
    if (!existsSync(directory)) {
      mkdirSync(directory, { recursive: true });
    }
    const filePath = path.join(directory, filename);
    // Ensure subdirectories exist
    const dir = path.dirname(filePath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    return new Promise((resolve, reject) => {
      writeFile(filePath, content, 'utf-8', (err) => {
        if (err) reject(err);
        else resolve(filePath);
      });
    });
  }

  private parseResponse(text: string): { filename: string | null; content: string } {
    const lines = text.trim().split('\n');
    const match = lines[0]?.match(/^\/\/\s*@file:\s*(.+)/);
    if (match) {
      const filename = match[1].trim();
      const content = lines.slice(1).join('\n').trim() + '\n';
      return { filename, content };
    }
    return { filename: null, content: text };
  }

  private inferFilename(prompt: string): string {
    const lower = prompt.toLowerCase();
    if (lower.includes('component')) return 'Component.tsx';
    if (lower.includes('test')) return 'test.spec.ts';
    if (lower.includes('style') || lower.includes('css')) return 'styles.css';
    if (lower.includes('api') || lower.includes('service')) return 'service.ts';
    return 'output.ts';
  }
}
