// Claude API integration placeholder
// Set ANTHROPIC_API_KEY environment variable to enable

export class ClaudeService {
  private apiKey: string | undefined;

  constructor() {
    this.apiKey = process.env.ANTHROPIC_API_KEY;
  }

  async streamTask(
    prompt: string,
    onChunk: (text: string, done: boolean) => void
  ): Promise<void> {
    if (!this.apiKey) {
      // Demo mode: simulate streaming response
      const demoResponse = `// Generated by Agent Garden\n// Task: ${prompt}\n\nconsole.log("Hello from Agent Garden!");`;
      const words = demoResponse.split(' ');
      for (const word of words) {
        await new Promise((r) => setTimeout(r, 100));
        onChunk(word + ' ', false);
      }
      onChunk('', true);
      return;
    }

    // Real Claude API integration (requires @anthropic-ai/sdk)
    const Anthropic = require('@anthropic-ai/sdk');
    const client = new Anthropic({ apiKey: this.apiKey });

    const stream = await client.messages.stream({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }],
    });

    for await (const event of stream) {
      if (
        event.type === 'content_block_delta' &&
        event.delta.type === 'text_delta'
      ) {
        onChunk(event.delta.text, false);
      }
    }
    onChunk('', true);
  }
}
